subarch: amd64
target: stage1
version_stamp: clang-musl-container-optimized
rel_type: clang-musl-container-optimized
profile: linux/amd64/clang-musl-container/bootstrapped/lto
snapshot_treeish: snapshot
source_subpath: clang-musl-container-bootstrap/stage3-amd64-clang-musl-container-bootstrap.tar.gz
compression_mode: gzip
update_seed: no