subarch: amd64
target: stage1
version_stamp: clang-musl-container-optimized
rel_type: clang-musl-container-optimized
profile: linux/amd64/clang-musl-container/bootstrapped/lto
snapshot_treeish: snapshot
source_subpath: bootstrap.tar
compression_mode: gzip
update_seed: no