subarch: amd64
target: stage1
version_stamp: musl-clang-container-bootstrap
rel_type: musl-clang-container-bootstrap
profile: linux/amd64/bootstrap-clang-musl-container
snapshot_treeish: snapshot
source_subpath: seed.tar
compression_mode: gzip
update_seed: no