subarch: amd64
target: stage1
version_stamp: clang-musl-container-bootstrap
rel_type: clang-musl-container-bootstrap
profile: linux/amd64/clang-musl-container/bootstrap
snapshot_treeish: snapshot
source_subpath: seed.tar
compression_mode: gzip
update_seed: no